name: uas_project
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pdf: ^3.11.0
  path_provider: ^2.0.9
  open_file: ^3.2.1
  intl: ^0.17.0
  bottom_sheet_expandable_bar: ^0.1.2
  adaptive_action_sheet: ^2.0.1
  path: ^1.8.0
  sqflite: ^2.0.0+4
  image_picker: ^1.0.8
  provider: ^6.0.2
  dio: ^4.0.6
  carousel_slider: ^4.1.1
  flutter_staggered_animations: ^1.0.0
  test: ^1.19.5
  sqflite_common_ffi: ^2.3.0+4
  sembast_web: ^2.2.0
  printing: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
